name: main

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y qemu-user-static
      - run: ./build.sh
        env:
          REGISTRY_ALT: ${{secrets.REGISTRY_ALT}}
      - run: ./clean.sh
